{% set name = "shapicant" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shapicant-{{ version }}.tar.gz
  sha256: 916e4afc070677be604dd49932b6f568cd1628d12804cff92469c69e5648e8d0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pandas
    - python >=3.6
    - scikit-learn
    - shap >=0.36.0
    - tqdm

test:
  imports:
    - shapicant

about:
  home: https://github.com/manuel-calzolari/shapicant
  summary: Feature selection package based on SHAP and target permutation, for pandas and Spark
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - manuel-calzolari
